module.exports = async function handler(req, res) {
  try {
    const city = String(req.query.city || "").trim(); const date = String(req.query.date || "").trim(); const comedian = String(req.query.comedian || "").trim();
    const view = String(req.query.view || "").trim(); const month = String(req.query.month || "").trim(); const calendarMode = view === "calendar"; const mapMode = view === "map";
    const rawWindow = req.query.window == null || req.query.window === "" ? 0 : Number(req.query.window);
    const validWindow = Number.isInteger(rawWindow) && rawWindow >= 0 && rawWindow <= 7;
    const windowDays = validWindow ? rawWindow : 0;
    const validMonth = value => { if (!/^\d{4}-(0[1-9]|1[0-2])$/.test(value)) return false; const [y,m]=value.split("-").map(Number); const d=new Date(Date.UTC(y,m-1,1)); return d.getUTCFullYear()===y && d.getUTCMonth()===m-1; };
    const validDate = value => { if (!/^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])$/.test(value)) return false; const [y,m,d]=value.split("-").map(Number); const parsed=new Date(Date.UTC(y,m-1,d)); return parsed.getUTCFullYear()===y && parsed.getUTCMonth()===m-1 && parsed.getUTCDate()===d; };
    if (!calendarMode && !mapMode && !comedian && (!city || !date)) return res.status(400).json({ error: "city and date are required unless searching by comedian" });
    if (calendarMode && !validMonth(month)) return res.status(400).json({ error: "calendar month must be a valid YYYY-MM" });
    if (!calendarMode && !mapMode && !comedian && !validDate(date)) return res.status(400).json({ error: "date must be a valid YYYY-MM-DD" });
    if (!calendarMode && !mapMode && !comedian && !validWindow) return res.status(400).json({ error: "window must be an integer from 0 to 7" });
    const supabaseUrl=process.env.SUPABASE_URL, supabaseKey=process.env.SUPABASE_ANON_KEY; if(!supabaseUrl||!supabaseKey)return res.status(500).json({error:"Supabase environment variables are missing"});
    let startDate,endDate;
    if(calendarMode){const [year,mon]=month.split("-").map(Number);startDate=`${month}-01`;endDate=new Date(Date.UTC(year,mon,0)).toISOString().slice(0,10)}
    else if(mapMode){startDate=new Date().toISOString().slice(0,10);const end=new Date();end.setUTCFullYear(end.getUTCFullYear()+2);endDate=end.toISOString().slice(0,10)}
    else {const effectiveDate=comedian?new Date().toISOString().slice(0,10):date;const target=new Date(`${effectiveDate}T12:00:00Z`);const start=new Date(target),end=new Date(target);if(!comedian)start.setUTCDate(start.getUTCDate()-windowDays);if(!comedian)end.setUTCDate(end.getUTCDate()+windowDays);else end.setUTCFullYear(end.getUTCFullYear()+2);startDate=start.toISOString().slice(0,10);endDate=end.toISOString().slice(0,10)}
    const venueSelect=mapMode?"venues(name,official_url,latitude,longitude,coordinates_verified_at)":"venues(name,official_url)";
    const params=new URLSearchParams({select:`id,event_name,starts_at,local_date,local_time,city,state_region,country,official_ticket_url,ticket_provider,status,verification_status,verification_reason,confidence_score,source_count,last_verified_at,comedians(name,tier,image_url,image_rights),${venueSelect}`,publishable:"eq.true",verification_status:"in.(verified,verified_2_source)",local_date:`gte.${startDate}`,order:"starts_at.asc"});params.append("local_date",`lte.${endDate}`);
    if(city&&!comedian&&!calendarMode&&!mapMode)params.set("city",`ilike.${city}`);if(comedian){params.set("comedians","not.is.null");params.set("comedians.name",`ilike.${comedian}`)}
    if(mapMode){params.set("venues.latitude","not.is.null");params.set("venues.longitude","not.is.null");params.set("venues.coordinates_verified_at","not.is.null");params.set("venues","not.is.null")}
    const response=await fetch(`${supabaseUrl}/rest/v1/shows?${params.toString()}`,{headers:{apikey:supabaseKey,Authorization:`Bearer ${supabaseKey}`}});if(!response.ok)return res.status(500).json({error:"Supabase query failed",details:await response.text()});const rows=await response.json();
    const safeRows=mapMode?rows.filter(row=>{const rawLat=row.venues?.latitude,rawLon=row.venues?.longitude;if(rawLat==null||rawLon==null||rawLat===''||rawLon==='')return false;const lat=Number(rawLat),lon=Number(rawLon);return Boolean(row.venues?.coordinates_verified_at)&&Number.isFinite(lat)&&Number.isFinite(lon)&&lat>=-90&&lat<=90&&lon>=-180&&lon<=180;}):rows;
    const events=safeRows.map(row=>({id:row.id,name:row.comedians?.name||"",eventName:row.event_name||row.comedians?.name||"",venue:row.venues?.name||"",city:row.city,state:row.state_region||"",country:row.country,date:row.local_date,time:row.local_time||"",tier:row.comedians?.tier||"",ticketUrl:row.official_ticket_url||"",ticketProvider:row.ticket_provider||"Official source",imageUrl:row.comedians?.image_url||"",verifiedAt:row.last_verified_at,verificationStatus:row.verification_status,verificationReason:row.verification_reason||"",confidenceScore:row.confidence_score||0,sourceCount:row.source_count||0,imageRights:row.comedians?.image_rights||"none",status:row.status,latitude:mapMode?Number(row.venues?.latitude):undefined,longitude:mapMode?Number(row.venues?.longitude):undefined,coordinatesVerifiedAt:mapMode?row.venues?.coordinates_verified_at:undefined}));
    res.setHeader("Cache-Control","s-maxage=300, stale-while-revalidate=600");return res.status(200).json({events,meta:{city,comedian,date:calendarMode||mapMode||comedian?null:date,month:calendarMode?month:null,window:calendarMode||mapMode||comedian?null:windowDays,count:events.length,mode:calendarMode?"supabase-calendar":mapMode?"supabase-map":"supabase-live",generatedAt:new Date().toISOString()}})
  } catch(error){console.error(error);return res.status(500).json({error:"Stand Up Seeker API failed",details:error.message})}
};
